apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: bucket-validation.providerceph.crossplane.io
  objectSelector:
    matchLabels:
      provider-ceph.crossplane.io/validation-required: "true" 
