apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: bucket-validation.providerceph.crossplane.io
  clientConfig:
    service:
      name: provider-ceph
      namespace: crossplane-system
      port: 9443
