#!/bin/bash

: "${TEST_KIND_NODES?= required}"
: "${REPO?= required}"

# This script reads a comma-delimited string TEST_KIND_NODES of kind node versions
# for kuttl tests to be run on, and generates the relevant files for each version.

IFS=', ' read -r -a kind_nodes <<< "$TEST_KIND_NODES"


# remove existing files
rm -f ./e2e/kind/*
rm -f ./e2e/kuttl/*

HEADER="# This file was auto-generated by hack/generate-tests.sh"

for kind_node in "${kind_nodes[@]}"
do
	# write kind config file for version
	major=${kind_node%.*}
	if [ ! -d "./e2e/kind" ]; then
		mkdir -p ./e2e/kind
	fi
	file=./e2e/kind/kind-config-${major}.yaml

	cat <<EOF > "${file}"
${HEADER}
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
EOF
	# write kuttl config file for version
	if [ ! -d "./e2e/kuttl" ]; then
		mkdir -p ./e2e/kuttl
	fi
	file=./e2e/kuttl/${REPO}-${major}.yaml

	# tests always use 'stable' testDir
	cat <<EOF > "${file}"
${HEADER}
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./e2e/tests/stable
kindConfig: e2e/kind/kind-config-${major}.yaml
startKIND: false
timeout: 90
EOF

done
