---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-provider-ceph-ceph-crossplane-io-v1alpha1-bucket
  failurePolicy: Ignore
  name: bucket.providerceph.crossplane.io
  rules:
  - apiGroups:
    - provider-ceph.ceph.crossplane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buckets
  sideEffects: None
