apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: provider-ceph
      namespace: crossplane-system
      path: /validate-provider-ceph-ceph-crossplane-io-v1alpha1-bucket
      port: 9443
  failurePolicy: Fail
  name: bucket-validation.providerceph.crossplane.io
  objectSelector:
    matchLabels:
      provider-ceph.crossplane.io/validation-required: "true"
  rules:
  - apiGroups:
    - provider-ceph.ceph.crossplane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buckets
  sideEffects: None
