name: Auto approve

on:
  pull_request: {}

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'github-actions[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
