name: Auto approve

on: 
  pull_request:
    branches:
      - 'release-candidate-'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
