name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.ref, 'refs/heads/release-candidate-')
    steps:
      - uses: hmarr/auto-approve-action@v4
